-- =============================================================================
-- Cuisine du Monde - Nantes : schéma Supabase
-- À exécuter dans l'éditeur SQL Supabase (ou via la CLI supabase).
-- =============================================================================

-- Table des restaurants
create table if not exists public.restaurants (
  id          bigint generated by default as identity primary key,
  name        text not null,
  rating      double precision,
  cuisine     text,
  address     text,
  city        text not null default 'Nantes',
  latitude    double precision,
  longitude   double precision,
  website     text,
  phone       text,
  source      text,                 -- osm | google_maps | manual | csv
  source_id   text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists restaurants_cuisine_idx on public.restaurants (cuisine);
create index if not exists restaurants_is_active_idx on public.restaurants (is_active);

-- Contrainte d'unicité utilisée par l'upsert du worker (scraper/)
create unique index if not exists restaurants_source_unique
  on public.restaurants (source, source_id)
  where source is not null and source_id is not null;

-- Mise à jour automatique de updated_at
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists restaurants_set_updated_at on public.restaurants;
create trigger restaurants_set_updated_at
  before update on public.restaurants
  for each row execute function public.set_updated_at();

-- =============================================================================
-- RLS : lecture publique des restaurants actifs.
-- Les écritures passent par la clé service role (côté serveur web / worker),
-- qui contourne la RLS. Aucune policy d'écriture n'est donc nécessaire ici.
-- =============================================================================
alter table public.restaurants enable row level security;

drop policy if exists "Lecture publique des restaurants actifs" on public.restaurants;
create policy "Lecture publique des restaurants actifs"
  on public.restaurants
  for select
  using (is_active = true);

-- =============================================================================
-- Rôle administrateur
-- L'app considère un utilisateur comme admin si auth.users.raw_app_meta_data
-- contient role = 'admin'. user_metadata n'est jamais utilisé pour les droits.
--
-- Promouvoir un utilisateur en admin (remplacer l'email) :
--
--   update auth.users
--   set raw_app_meta_data = raw_app_meta_data || '{"role":"admin"}'::jsonb
--   where email = 'admin@cuisine-du-monde.local';
--
-- L'utilisateur doit se reconnecter pour rafraîchir son token.
-- =============================================================================

-- =============================================================================
-- Storage : bucket "Images" (photos de profil)
-- Dashboard : bucket public, MIME autorisés = image/jpeg, image/png, image/gif
-- L'upload passe par /api/profile/avatar (service role) : les policies ci-dessous
-- sont optionnelles mais recommandées si tu veux aussi un upload direct client.
-- =============================================================================

-- insert / update / delete : uniquement son dossier avatars/{user_id}/
drop policy if exists "Users upload own avatar" on storage.objects;
create policy "Users upload own avatar"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'Images'
    and (storage.foldername(name))[1] = 'avatars'
    and (storage.foldername(name))[2] = auth.uid()::text
  );

drop policy if exists "Users update own avatar" on storage.objects;
create policy "Users update own avatar"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'Images'
    and (storage.foldername(name))[1] = 'avatars'
    and (storage.foldername(name))[2] = auth.uid()::text
  );

drop policy if exists "Users delete own avatar" on storage.objects;
create policy "Users delete own avatar"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'Images'
    and (storage.foldername(name))[1] = 'avatars'
    and (storage.foldername(name))[2] = auth.uid()::text
  );

-- lecture publique des fichiers du bucket Images
drop policy if exists "Public read Images bucket" on storage.objects;
create policy "Public read Images bucket"
  on storage.objects for select
  to public
  using (bucket_id = 'Images');
